from __future__ import annotations

from pathlib import Path
from typing import Any

from kodex.file_writer import write_files
from kodex.repo_scanner import scan_repo
from kodex.task_planner import build_plan


def _readme_content(project: dict[str, Any], task: str) -> str:
    name = project.get("name", "project")
    stack = ", ".join(project.get("stack", [])) or "unknown"
    commands = project.get("commands", {})

    command_lines = "\n".join(
        f"- `{command_name}`: `{command}`" for command_name, command in commands.items()
    ) or "- No commands detected yet."

    return f"""# {name}

Generated by Kodex.

## Purpose

This repository is tracked by Kodex, the BlackMamba Dev Agent.

Original task:

```txt
{task}
```

## Detected Stack

{stack}

## Common Commands

{command_lines}

## Kodex Notes

- Keep changes small and reversible.
- Run checks before committing.
- Avoid committing secrets or generated dependency folders.
"""


def _safe_test_name(project_name: str) -> str:
    clean = project_name.replace("-", "_").replace(" ", "_").lower()
    clean = "".join(char if char.isalnum() or char == "_" else "_" for char in clean)
    clean = "_".join(part for part in clean.split("_") if part)
    return clean or "project"


def _smoke_test_content(project: dict[str, Any], suffix: str = "") -> str:
    name = _safe_test_name(project.get("name", "project"))
    function_name = f"test_{name}_smoke{suffix}"
    return f'''def {function_name}():
    """Basic smoke test generated by Kodex."""
    assert True
'''


def _next_available_smoke_test(root: Path, project: dict[str, Any]) -> tuple[str, str]:
    name = _safe_test_name(project.get("name", "project"))
    base = Path("tests") / f"test_{name}_smoke.py"

    if not (root / base).exists():
        return str(base), _smoke_test_content(project)

    for index in range(2, 100):
        candidate = Path("tests") / f"test_{name}_smoke_{index}.py"
        if not (root / candidate).exists():
            return str(candidate), _smoke_test_content(project, suffix=f"_{index}")

    raise RuntimeError("could not find available smoke test filename")


def propose_patch(task: str, repo_root: str | Path = ".") -> dict[str, Any]:
    """Generate a conservative file patch proposal for simple tasks."""
    root = Path(repo_root).expanduser().resolve()
    project = scan_repo(root)
    plan = build_plan(task, project)
    task_lower = task.lower()

    files: dict[str, str] = {}

    if "readme" in task_lower:
        files["README.md"] = _readme_content(project, task)

    if "smoke" in task_lower or "test" in task_lower:
        path, content = _next_available_smoke_test(root, project)
        files[path] = content

    if not files:
        files["KODEX_TASK.md"] = f"""# Kodex Task

```txt
{task}
```

## Plan

""" + "\n".join(f"{index}. {step}" for index, step in enumerate(plan["steps"], start=1)) + "\n"

    return {
        "task": task,
        "project": project,
        "plan": plan,
        "files": files,
        "mode": "proposal",
    }


def apply_patch(task: str, repo_root: str | Path = ".", *, force: bool = False) -> dict[str, Any]:
    """Generate and apply a conservative patch."""
    proposal = propose_patch(task, repo_root)
    write_result = write_files(repo_root, proposal["files"], force=force)
    return {
        "proposal": proposal,
        "write_result": write_result,
    }
